version: '3.8'

services:
  produto-service:
    build:
      context: ./api-service/app/produto   # Caminho para o diretório onde está o código do backend de produto
      dockerfile: Dockerfile               # Nome do Dockerfile para o backend
    container_name: produto_service
    ports:
      - "8001:8000"                       # Mapeamento de porta do serviço de produto
    volumes:
      - ./app/logs/produto:/app/logs
    env_file:
      - .env

  usuario-service:
    build:
      context: ./api-service/app/usuario   # Caminho para o diretório onde está o código do backend de usuário
      dockerfile: Dockerfile               # Nome do Dockerfile para o backend
    container_name: usuario_service
    ports:
      - "8002:8000"                       # Mapeamento de porta do serviço de usuário
    volumes:
      - ./app/logs/usuario:/app/logs
    env_file:
      - .env